# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93d735c3464573af3f28621d64a8079fe6483332aba8d4e167d1e4be11171b863b51218bc0f53dc4862b72e17cbd117ea5e4c7bf21c43d6eb6973e27792d54ec

test:
  secret_key_base: 85cb7b82db4e268e089cb10dd12cdc955de891e6603eabc632b8579b85211430c0b307f5aff74a5a6fe431b221940c1fad5d6701f583c8c71dad04955863dffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
